# -*- coding: utf-8 -*-
"""MUSCLE_MASS_PRED_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCmtXSSncdG1bK6z879dwmIBXE8tZ5yz

# **Extract**
"""

import pandas as pd

# === Upload Dataset 1 ===
from google.colab import files
files.upload()

df = pd.read_csv("health_fitness_dataset (1).csv")
df.head()

df_unique = df.drop_duplicates(subset='participant_id', keep='first').reset_index(drop=True)
df_unique.head()

# === Upload Dataset 2 ===
files.upload()
df1 = pd.read_csv("gym_members_exercise_tracking_synthetic_data.csv")
df1.head()

df_unique['activity_type'].unique()

df_unique['activity_type'].value_counts()

df1['Experience_Level'].unique()

"""# ***Transform***"""

activity_mapping = {
    'Yoga': 1,
    'Weight Training': 3,
    'HIIT': 2,
    'Dancing': 1,
    'Cycling': 2,
    'Basketball': 1,
    'Tennis': 1,
    'Walking': 2,
    'Swimming': 2,
    'Running': 2
}


df_unique['activity_type'] = df_unique['activity_type'].astype(str)


df_unique['exercise_group'] = df_unique['activity_type'].map(activity_mapping)

df_unique.head()

df_unique['exercise_group'].unique()

df1['Experience_Level'] = df1['Experience_Level'].astype(pd.Int64Dtype())
df_unique['exercise_group'] = df_unique['exercise_group'].astype(int)

"""# ***Merging Datasets***"""

fitness_dataset= pd.merge(df_unique, df1, left_on='exercise_group', right_on='Experience_Level', how='left')

fitness_dataset.head()

fitness_dataset.tail()

fitness_dataset.shape

"""# ***Preliminary EDA***"""

fitness_dataset.info()

fitness_dataset.isnull().sum().sort_values(ascending=False)

df.isnull().mean() * 100

fitness_dataset.duplicated().sum()

fitness_dataset.describe(include='all')

fitness_dataset.columns

fitness_dataset.drop(columns=[
    'participant_id', 'date', 'age', 'gender', 'height_cm', 'weight_kg',
    'bmi', 'duration_minutes', 'intensity',
    'calories_burned', 'daily_steps',
    'resting_heart_rate', 'blood_pressure_systolic',
    'blood_pressure_diastolic', 'endurance_level',
    'stress_level', 'hydration_level', 'health_condition',
], inplace=True)

fitness_dataset.columns

fitness_dataset.isnull().sum()

"""# ***Handeling  Missing Values***"""

num_cols = [
    'Age', 'Weight (kg)', 'Height (m)', 'Max_BPM', 'Avg_BPM', 'Resting_BPM',
    'Session_Duration (hours)', 'Calories_Burned', 'Fat_Percentage',
    'Water_Intake (liters)', 'Workout_Frequency (days/week)', 'Experience_Level', 'BMI'
]

for col in num_cols:
    fitness_dataset[col] = pd.to_numeric(fitness_dataset[col], errors='coerce')

for col in num_cols:
    median_value = fitness_dataset[col].median()
    fitness_dataset[col].fillna(median_value, inplace=True)


cat_cols = ['Gender', 'Workout_Type']
for col in cat_cols:
    mode_value = fitness_dataset[col].mode()[0]
    fitness_dataset[col].fillna(mode_value, inplace=True)

fitness_dataset[num_cols + cat_cols].isnull().sum()

"""# ***Feature eng***"""

#Muscle Mass(target)
fitness_dataset['muscle_mass'] = fitness_dataset['Weight (kg)'] * (1 - fitness_dataset['Fat_Percentage']/100) * 0.85
#sleep effeciency
fitness_dataset['Sleep_Efficiency'] = fitness_dataset['sleep_hours'] / fitness_dataset['Workout_Frequency (days/week)']
#Training Consistency Index
fitness_dataset['Training_Consistency'] = fitness_dataset['Workout_Frequency (days/week)'] * fitness_dataset['Session_Duration (hours)']

"""# ***Detect Outliers***"""

# === Detect Outliers Using IQR ===

def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]
    return outliers, lower, upper

cols_to_check = [
    'activity_type', 'avg_heart_rate', 'sleep_hours', 'smoking_status',
    'fitness_level', 'exercise_group', 'Age', 'Gender', 'Weight (kg)',
    'Height (m)', 'Max_BPM', 'Avg_BPM', 'Resting_BPM',
    'Session_Duration (hours)', 'Calories_Burned', 'Workout_Type',
    'Fat_Percentage', 'Water_Intake (liters)',
    'Workout_Frequency (days/week)', 'Experience_Level', 'BMI','muscle_mass','Sleep_Efficiency','Training_Consistency'
]

outlier_summary = {}

for col in cols_to_check:

    if fitness_dataset[col].dtype in ['int64', 'float64']:
        outliers, lower, upper = detect_outliers_iqr(fitness_dataset, col)
        outlier_summary[col] = len(outliers)
        print(f"Column: {col}")
        print(f" • Outliers found: {len(outliers)}")
        print(f" • Lower Bound: {lower}")
        print(f" • Upper Bound: {upper}")
        print("-" * 40)
    else:
        print(f"Column: {col} is non-numeric, skipped for outlier detection.")
        print("-" * 40)

outlier_summary

import matplotlib.pyplot as plt
import seaborn as sns

# Columns to visualize
numeric_cols = fitness_dataset.select_dtypes(include=['number']).columns


plt.figure(figsize=(15, len(numeric_cols) * 2.5))

colors = ['skyblue', 'lightgreen', 'salmon', 'violet', 'orange', 'lightcoral', 'cyan']
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(x=fitness_dataset[col], color=colors[i % len(colors)])
    plt.title(f'Boxplot of {col}', fontsize=10)
    plt.xlabel('')
    plt.grid(axis='x', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""# ***Winsorizing / Capping Outliers Using IQR***"""

def cap_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Apply capping (values below lower set to lower, above upper set to upper)
    df[column] = df[column].clip(lower, upper)

    return lower, upper


columns_with_outliers = [
    'avg_heart_rate', 'sleep_hours', 'Weight (kg)', 'Fat_Percentage', 'BMI','muscle_mass','Sleep_Efficiency','Training_Consistency'
]

capping_ranges = {}

for col in columns_with_outliers:
    lower, upper = cap_outliers_iqr(fitness_dataset, col)
    capping_ranges[col] = (lower, upper)
    print(f" Capped column: {col}")
    print(f"   Lower Bound = {lower}")
    print(f"   Upper Bound = {upper}")
    print("-" * 40)



"""# ***EDA(Visualization and corr)***

*   BMI vs Weight
*   Duratoin vs Calories Burned

*   correlation heatmap
*   boxplot after capping

*   Distribution of activity groups
*   Count of Workout Type

*   Count of Smoking Status
*   Muscle Mass and Workout Type








"""

import seaborn as sns
import matplotlib.pyplot as plt

# Select only numeric columns from the dataset for correlation calculation
numeric_cols_dataset = fitness_dataset.select_dtypes(include=['number']).columns

# Calculate the correlation matrix for the numeric columns in 'dataset'
corr_matrix_dataset = fitness_dataset[numeric_cols_dataset].corr()

# Create the heatmap
plt.figure(figsize=(15, 12))
sns.heatmap(corr_matrix_dataset, annot=True, cmap='magma', fmt=".2f", linewidths=.5)
plt.title('Correlation Heatmap for Dataset Columns', fontsize=16)
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

#Top 10 correlated Features
import pandas as pd


# Select numeric columns only
numeric_df = fitness_dataset.select_dtypes(include=['number'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()

# Display result
corr_matrix


corr_pairs = corr_matrix.unstack().reset_index()
corr_pairs.columns = ['Feature1', 'Feature2', 'Correlation']

# Remove self-correlations + duplicate pairs
corr_pairs = corr_pairs[corr_pairs['Feature1'] != corr_pairs['Feature2']]
corr_pairs = corr_pairs.drop_duplicates(subset=['Correlation'])

# Sort by highest correlation
top_corr = corr_pairs.sort_values(by='Correlation', ascending=False).head(10)
top_corr

#drop one column from correlated columns which have value =1
fitness_dataset.drop(columns=["exercise_group"], inplace=True)

import matplotlib.pyplot as plt
import seaborn as sns

# Columns to visualize
numeric_cols = fitness_dataset.select_dtypes(include=['number']).columns


plt.figure(figsize=(15, len(numeric_cols) * 2.5))

colors = ['skyblue', 'lightgreen', 'salmon', 'violet', 'orange', 'lightcoral', 'cyan']
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(x=fitness_dataset[col], color=colors[i % len(colors)])
    plt.title(f'Boxplot of {col}', fontsize=10)
    plt.xlabel('')
    plt.grid(axis='x', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.scatterplot(data=fitness_dataset, x='Weight (kg)', y='BMI', alpha=0.5,color='royalblue')
plt.title('Scatterplot of BMI vs. Weight (kg)')
plt.xlabel('Weight (kg)')
plt.ylabel('BMI')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

plt.scatter(fitness_dataset['Session_Duration (hours)'], fitness_dataset['Calories_Burned'],color='crimson')
plt.xlabel('Session_Duration (hours)')
plt.ylabel('Calories_Burned')
plt.title('Session Duration vs Calories Burned')
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt


order = fitness_dataset["activity_type"].value_counts().index

plt.figure(figsize=(10,6))
sns.countplot(data=fitness_dataset, x="activity_type", order=order, palette="viridis")


plt.xticks(rotation=0)

plt.ylabel("Count")
plt.xlabel("Activity Type")
plt.title("Activity Type Distribution (Sorted High → Low)")

plt.show()

plt.figure(figsize=(6,4))
fitness_dataset['Workout_Type'].value_counts().plot(kind='bar')

plt.title("Count of Workout Type")
plt.xlabel("Workout Type")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
fitness_dataset['smoking_status'].value_counts().plot(
    kind='bar',
    color=['#3A86FF', '#FF006E', '#8338EC']

)

plt.title("Count of Smoking Status")
plt.xlabel("Smoking Status")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

print(fitness_dataset.columns.tolist())

plt.figure(figsize=(10, 6))
sns.violinplot(data=fitness_dataset, x='Workout_Type', y='muscle_mass')

plt.title('Muscle Mass Distribution by Workout Type')
plt.xlabel('Workout_Type')
plt.ylabel('muscle_mass')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# ***Load***"""

fitness_dataset.to_csv("fitness_dataset_cleaned.csv", index=False)



files.download("fitness_dataset_cleaned.csv")